<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="FirebirdSql.Data.FirebirdClient" Version="10.3.4" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ElPrado.Core\ElPrado.Core.csproj" />
    <ProjectReference Include="..\ElPrado.Dto\ElPrado.Dto.csproj" />
  </ItemGroup>

</Project>
