stages:
  - build
  
before_script:
  - docker info

build_develop:
  stage: build
  script:
    - docker build -t "elpradowebapi" .
    - docker rm -f elpradowebapi || true
    - docker run --restart=always --net netpub --ip 210.1.0.101 -p 222:80 --name elpradowebapi -d -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro --env ASPNETCORE_ENVIRONMENT=Staging elpradowebapi
  only:
    - develop
