<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="mercadopago-sdk" Version="2.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ElPrado.Data\ElPrado.Data.csproj" />
    <ProjectReference Include="..\ElPrado.Dto\ElPrado.Dto.csproj" />
  </ItemGroup>

</Project>
