CREATE TABLE ESTADOS_DEUDAS (
  COD_ESTADO_DEUDA            T_CLAVE_UNICA NOT NULL,
  ESTADO                      VARCHAR(50) NOT NULL,
  PERMITIR_IMPUTAR            T_BOOLEAN,
  ACTIVA                      T_BOOLEAN DEFAULT 1,
  MUESTRA_MENSAJE_ALERTA      T_BOOLEAN,
  MENSAJE_ALERTA              BLOB SUB_TYPE 1 SEGMENT SIZE 80,
  TIEMPO_MENSAJE              INTEGER DEFAULT 0 NOT NULL,
  COD_SUCURSAL_SINCRONIZACION T_CLAVE_UNICA,
  FECHA_SINCRONIZACION        T_FECHA_HORA,
  MODIFICADO_SINCRONIZACION   T_CLAVE_UNICA,
  MOSTRAR_DEUDA               T_BOOLEAN,
  BLOQUEAR_MEDIO_COBRO        T_BOOLEAN
);
ALTER TABLE ESTADOS_DEUDAS ADD CONSTRAINT PK_ESTADOS_DEUDAS PRIMARY KEY (COD_ESTADO_DEUDA);