CREATE TABLE PROPUESTAS_TITULARES (
  COD_PROPUESTA               T_CLAVE_UNICA NOT NULL,
  COD_CLIENTE                 T_CLAVE_UNICA NOT NULL,
  ORDEN                       SMALLINT NOT NULL,
  FECHA_ALTA                  T_FECHA NOT NULL,
  FECHA_BAJA                  T_FECHA,
  COD_CLIENTE_AUTORIZA        T_CLAVE_UNICA,
  COD_CLIENTE_AUTORIZA_BAJA   T_CLAVE_UNICA,
  COD_USUARIO                 T_CLAVE_UNICA NOT NULL,
  COD_USUARIO_BAJA            T_CLAVE_UNICA,
  COD_SUCURSAL_SINCRONIZACION T_CLAVE_UNICA,
  FECHA_SINCRONIZACION        T_FECHA_HORA,
  MODIFICADO_SINCRONIZACION   T_CLAVE_UNICA
);
ALTER TABLE PROPUESTAS_TITULARES ADD CONSTRAINT PK_PROPUESTAS_TITULARES PRIMARY KEY (COD_PROPUESTA, COD_CLIENTE, FECHA_ALTA);