CREATE TABLE PROPUESTA (
  COD_PROPUESTA               T_CLAVE_UNICA NOT NULL,
  COD_TIPO_PROPUESTA          T_CLAVE_UNICA NOT NULL,
  LEGAJO                      INTEGER NOT NULL,
  FECHA                       T_FECHA,
  FECHA_BAJA                  T_FECHA,
  COD_PARCELA                 T_CLAVE_UNICA,
  COD_SUCURSAL_SINCRONIZACION T_CLAVE_UNICA,
  FECHA_SINCRONIZACION        T_FECHA_HORA,
  MODIFICADO_SINCRONIZACION   INTEGER,
  OBSERVACIONES               BLOB SUB_TYPE 1 SEGMENT SIZE 80,
  COD_ESTADO_DEUDA            T_CLAVE_UNICA NOT NULL,
  ULTIMA_REVISION             T_FECHA
);
ALTER TABLE PROPUESTA ADD CONSTRAINT PK_PROPUESTA PRIMARY KEY (COD_PROPUESTA);