CREATE PROCEDURE GET_DATOS_TITULAR_DNI_CUIT (
  PROPUESTA INTEGER,
  DNI_CUIT BIGINT
)
RETURNS (
  COD_CLIENTE INTEGER,
  NOMBRE VARCHAR(100),
  TIPO_DOCUMENTO VARCHAR(6),
  NRO_DOCUMENTO NUMERIC(8, 0),
  CUIT NUMERIC(11, 0),
  CLAVE_ACCESO VARCHAR(40)
)
AS
BEGIN
  FOR
    SELECT FIRST 1 C.COD_CLIENTE, C.NOMBRE, C.TIPO_DOCUMENTO, C.NRO_DOCUMENTO, C.CUIT, C.CLAVE_ACCESO
    FROM CLIENTES C
    WHERE (C.NRO_DOCUMENTO = :DNI_CUIT OR C.CUIT = :DNI_CUIT)
    AND C.FECHA_BAJA IS NULL AND C.FECHA_FALLECIMIENTO IS NULL
    AND EXISTS (SELECT 1 FROM PROPUESTA P
      INNER JOIN PROPUESTAS_TITULARES PT ON PT.COD_PROPUESTA = P.COD_PROPUESTA
      INNER JOIN ESTADOS_DEUDAS ED ON ED.COD_ESTADO_DEUDA = P.COD_ESTADO_DEUDA
      WHERE PT.FECHA_BAJA IS NULL AND P.FECHA_BAJA IS NULL AND ED.ACTIVA = 1
      AND P.LEGAJO = :PROPUESTA)
    INTO :COD_CLIENTE, :NOMBRE, :TIPO_DOCUMENTO, :NRO_DOCUMENTO, :CUIT, :CLAVE_ACCESO
  DO
  BEGIN
    SUSPEND;
  END
END
;