/*
  MCP API v2 - campo funcional AL_DIA.

  Aplicada manualmente en Firebird el 26/09/2026.
  El procedimiento CONSULTA_RESUMEN_CUENTAS quedó sin la sección histórica
  de CIBA y sin proyectar AL_DIA; este archivo refleja esa versión aplicada.
*/

ALTER TABLE ESTADOS_DEUDAS ADD AL_DIA T_BOOLEAN;

SET TERM ^;

ALTER PROCEDURE CONSULTA_RESUMEN_CUENTAS (
    COD_PROPUESTA INTEGER,
    MOSTRAR_BAJA SMALLINT,
    MOSTRAR_INACTIVA SMALLINT,
    FECHA_INTERES DATE,
    FECHA_HASTA DATE)
RETURNS (
    TIPO CHAR(2),
    ES_REFINANCIACION SMALLINT,
    ES_DOCUMENTADO SMALLINT,
    CATEGORIA VARCHAR(50),
    ESTADO VARCHAR(50),
    IMPORTE NUMERIC(18, 2),
    PRECIO_DOLAR NUMERIC(18, 2),
    FECHA_INICIO DATE,
    PRIMER_CUOTA DATE,
    FECHA_BAJA DATE,
    COBRADOR VARCHAR(50),
    CLIENTE VARCHAR(100),
    COD_CLIENTE INTEGER,
    ZONA_COBRANZA VARCHAR(50),
    COBRADOR_ZONA VARCHAR(105),
    CODIGO INTEGER,
    COD_MEDIO_COBRO INTEGER,
    COMERCIALIZADORA VARCHAR(50),
    CUOTAS INTEGER,
    CUOTA_DESDE DATE,
    CUOTA_HASTA DATE,
    IMPORTE_VENCIDO NUMERIC(18, 2),
    INTERES NUMERIC(18, 2),
    IMPORTE_A_VENCER NUMERIC(18, 2),
    DESCUENTO_VENCIDO NUMERIC(18, 2),
    DESCUENTO_A_VENCER NUMERIC(18, 2),
    DEUDA NUMERIC(18, 2),
    TOTAL NUMERIC(18, 2),
    PORC_CANCELADO NUMERIC(18, 2),
    COD_CAT_RECARGO INTEGER,
    ES_INDEPENDIENTE SMALLINT,
    ES_PRECIO_DIFERENCIAL SMALLINT)
AS
DECLARE VARIABLE IMPORTE_ORIGINAL NUMERIC(18, 2);
DECLARE VARIABLE IMPORTE_CANCELADO NUMERIC(18, 2);
DECLARE VARIABLE MOSTRAR_DEUDA SMALLINT;
DECLARE VARIABLE INICIAR_CON_INHUMACION SMALLINT;
BEGIN
  --> Muestra las cuentas de una propuesta con un resume de la deuda
  --> 22/01/2015
  --> Se agrego el precio en dolar
  --> 06/05/2015
  --> Se sacaron los creditos que no son provenientes de planes de ventas
  --> 15/07/2015
  --> Se borra la tabla PLANES_VENTAS_CREDITOS
  --> Se considera el anticipo en cuotas
  --> 30/10/2015
  --> Se agrega la deuda en Ciba de los PI-II
  --> 22/06/2017
  --> Se agrega el interes de financiacion
  --> 18/09/2017
  --> Se agrega el porcentaje cancelado de los creditos
  --> 04/02/2023
  --> Devuelve datos del cliente de la cuenta
  --> 19/07/2025
  --> Se agregan los campos DEUDA y ES_PRECIO_DIFERENCIAL
  --> 10/09/2025
  --> Se agrega la primer cuota y se quita la seccion Deuda en Ciba

  CUOTA_DESDE = NULL;
  CUOTA_HASTA = NULL;
  IMPORTE_VENCIDO = 0;
  INTERES = 0;
  IMPORTE_A_VENCER = 0;
  DESCUENTO_VENCIDO = 0;
  DESCUENTO_A_VENCER = 0;
  TOTAL = 0;
  COD_CAT_RECARGO = NULL;
  PORC_CANCELADO = 0;
  ES_INDEPENDIENTE = 0;
  ES_PRECIO_DIFERENCIAL = 0;

  TIPO = 'CR';
  FOR
    SELECT C.ES_REFINANCIACION, C.ES_DOCUMENTADO, CT.CATEGORIA, E.ESTADO, C.IMPORTE_ORIGINAL,
      C.IMPORTE_ORIGINAL + C.INTERES, C.PRECIO_DOLAR,
      C.FECHA_INICIO, C.FECHA_BAJA, CO.NOMBRE, Z.DESCRIPCION,
      CO.NOMBRE || CASE WHEN Z.DESCRIPCION = CO.NOMBRE THEN '' ELSE ' - ' || Z.DESCRIPCION END,
      C.COD_CREDITO, C.COD_MEDIO_COBRO, E.MOSTRAR_DEUDA,
      (SELECT CL.NOMBRE FROM CLIENTES CL WHERE CL.COD_CLIENTE = C.COD_CLIENTE), C.COD_CLIENTE,
      (SELECT EC.NOMBRE FROM ENTIDADES EC WHERE EC.COD_ENTIDAD = C.COD_COMERCIALIZADORA),
      COALESCE((SELECT COUNT(*) FROM CUOTAS CU WHERE CU.COD_CREDITO = C.COD_CREDITO), 0),
      (SELECT MIN(CU.FECHA_VENCIMIENTO) FROM CUOTAS CU WHERE CU.COD_CREDITO = C.COD_CREDITO)
    FROM CREDITOS C
    INNER JOIN CAT_CREDITOS CT ON CT.COD_CAT_CREDITO = C.COD_CAT_CREDITO
    INNER JOIN ESTADOS_DEUDAS E ON E.COD_ESTADO_DEUDA = C.COD_ESTADO_DEUDA
    LEFT OUTER JOIN MEDIOS_COBROS M ON M.COD_MEDIO_COBRO = C.COD_MEDIO_COBRO
    LEFT OUTER JOIN ZONA_COBRANZA Z ON Z.COD_ZONA_COBRANZA = M.COD_ZONA_COBRANZA
    LEFT OUTER JOIN COBRADORES CO ON CO.COD_COBRADOR = Z.COD_COBRADOR
    WHERE C.COD_PROPUESTA = :COD_PROPUESTA
      AND (:MOSTRAR_BAJA = 1 OR C.FECHA_BAJA IS NULL)
      AND (:MOSTRAR_INACTIVA = 1 OR E.ACTIVA = 1)
      AND C.NUMERO_FACTURA IS NULL
    INTO :ES_REFINANCIACION, :ES_DOCUMENTADO, :CATEGORIA, :ESTADO,
      :IMPORTE_ORIGINAL, :IMPORTE, :PRECIO_DOLAR,
      :FECHA_INICIO, :FECHA_BAJA, :COBRADOR, :ZONA_COBRANZA, :COBRADOR_ZONA,
      :CODIGO, :COD_MEDIO_COBRO, :MOSTRAR_DEUDA,
      :CLIENTE, :COD_CLIENTE, :COMERCIALIZADORA, :CUOTAS, :PRIMER_CUOTA
  DO
  BEGIN
    PORC_CANCELADO = 0;
    IF (:IMPORTE_ORIGINAL > 0) THEN
    BEGIN
      SELECT COALESCE(SUM(CU.MONTO), 0)
      FROM CUOTAS CU
      WHERE CU.COD_CREDITO = :CODIGO
      AND CU.FECHA_RENDICION IS NOT NULL AND CU.ANULADO = 0
      INTO :IMPORTE_CANCELADO;
      PORC_CANCELADO = :IMPORTE_CANCELADO / :IMPORTE_ORIGINAL * 100;
      IF (:PORC_CANCELADO > 100) THEN
      BEGIN
        PORC_CANCELADO = 100;
      END
    END

    IF ((:FECHA_INTERES IS NOT NULL) AND (:FECHA_HASTA IS NOT NULL)) THEN
    BEGIN
      CUOTA_DESDE = NULL;
      CUOTA_HASTA = NULL;
      IMPORTE_VENCIDO = 0;
      INTERES = 0;
      IMPORTE_A_VENCER = 0;
      DESCUENTO_VENCIDO = 0;
      DESCUENTO_A_VENCER = 0;
      DEUDA = 0;
      TOTAL = 0;
      COD_CAT_RECARGO = NULL;
      IF (:MOSTRAR_DEUDA = 1) THEN
      BEGIN
        SELECT C.CUOTA_DESDE, C.CUOTA_HASTA, C.IMPORTE_VENCIDO + C.FINANCIACION_VENCIDO,
          C.INTERES, C.IMPORTE_A_VENCER + C.FINANCIACION_A_VENCER, C.DESCUENTO_VENCIDO,
          C.DESCUENTO_A_VENCER, C.DEUDA, C.TOTAL, C.COD_CAT_RECARGO
        FROM CALCULAR_INTERES_CR(:CODIGO, :FECHA_INTERES, :FECHA_HASTA, 0) C
        INTO :CUOTA_DESDE, :CUOTA_HASTA, :IMPORTE_VENCIDO, :INTERES, :IMPORTE_A_VENCER,
          :DESCUENTO_VENCIDO, :DESCUENTO_A_VENCER, :DEUDA, :TOTAL, :COD_CAT_RECARGO;
        IF (:CUOTA_DESDE IS NULL) THEN
        BEGIN
          SELECT MIN(C.FECHA_VENCIMIENTO)
          FROM CUOTAS C
          WHERE C.COD_CREDITO = :CODIGO
          AND C.FECHA_RENDICION IS NULL AND C.ANULADO = 0
          AND C.REFINANCIADO_POR IS NULL
          INTO :CUOTA_DESDE;
        END
      END
    END
    SUSPEND;
  END

  TIPO = 'CP';
  ES_REFINANCIACION = 0;
  ES_DOCUMENTADO = 0;
  PRECIO_DOLAR = 0;
  PORC_CANCELADO = 0;
  FOR
    SELECT CT.CATEGORIA, E.ESTADO, C.IMPORTE, C.FECHA_INICIO, C.PRIMER_CUOTA, C.FECHA_BAJA,
      CO.NOMBRE, Z.DESCRIPCION,
      CO.NOMBRE || CASE WHEN Z.DESCRIPCION = CO.NOMBRE THEN '' ELSE ' - ' || Z.DESCRIPCION END,
      C.COD_CONFIGURACION, C.COD_MEDIO_COBRO, E.MOSTRAR_DEUDA, C.ES_INDEPENDIENTE,
      (SELECT CL.NOMBRE FROM CLIENTES CL WHERE CL.COD_CLIENTE = C.COD_CLIENTE), C.COD_CLIENTE,
      (SELECT EC.NOMBRE FROM ENTIDADES EC WHERE EC.COD_ENTIDAD = C.COD_COMERCIALIZADORA),
      COALESCE((SELECT COUNT(*) FROM CUOTAS_PERIODICAS CU WHERE CU.COD_CONFIGURACION = C.COD_CONFIGURACION), 0),
      IIF(C.COD_CONFIGURACION_IGUAL IS NOT NULL, 1, 0), C.INICIAR_CON_INHUMACION
    FROM CONFIG_CUOTAS_PERIODICAS C
    INNER JOIN CAT_CUOTAS_PERIODICAS CT ON CT.COD_CAT_CUOTA_PERIODICA = C.COD_CAT_CUOTA_PERIODICA
    INNER JOIN ESTADOS_DEUDAS E ON E.COD_ESTADO_DEUDA = C.COD_ESTADO_DEUDA
    LEFT OUTER JOIN MEDIOS_COBROS M ON M.COD_MEDIO_COBRO = C.COD_MEDIO_COBRO
    LEFT OUTER JOIN ZONA_COBRANZA Z ON Z.COD_ZONA_COBRANZA = M.COD_ZONA_COBRANZA
    LEFT OUTER JOIN COBRADORES CO ON CO.COD_COBRADOR = Z.COD_COBRADOR
    WHERE C.COD_PROPUESTA = :COD_PROPUESTA
      AND (:MOSTRAR_BAJA = 1 OR C.FECHA_BAJA IS NULL)
      AND (:MOSTRAR_INACTIVA = 1 OR E.ACTIVA = 1)
    INTO :CATEGORIA, :ESTADO, :IMPORTE, :FECHA_INICIO, :PRIMER_CUOTA, :FECHA_BAJA,
      :COBRADOR, :ZONA_COBRANZA, :COBRADOR_ZONA, :CODIGO, :COD_MEDIO_COBRO,
      :MOSTRAR_DEUDA, :ES_INDEPENDIENTE, :CLIENTE, :COD_CLIENTE, :COMERCIALIZADORA,
      :CUOTAS, :ES_PRECIO_DIFERENCIAL, :INICIAR_CON_INHUMACION
  DO
  BEGIN
    IF (:INICIAR_CON_INHUMACION = 1) THEN
    BEGIN
      IF (:CUOTAS = 0 AND NOT EXISTS(SELECT 1 FROM DET_INHUMADOS DI
        INNER JOIN PROPUESTA P ON P.COD_PROPUESTA = DI.COD_PROPUESTA AND P.COD_PARCELA = DI.COD_PARCELA
        INNER JOIN CONFIG_CUOTAS_PERIODICAS C ON C.COD_PROPUESTA = P.COD_PROPUESTA
        WHERE C.COD_CONFIGURACION = :CODIGO)) THEN
      BEGIN
        PRIMER_CUOTA = NULL;
      END
    END

    IF ((:FECHA_INTERES IS NOT NULL) AND (:FECHA_HASTA IS NOT NULL)) THEN
    BEGIN
      CUOTA_DESDE = NULL;
      CUOTA_HASTA = NULL;
      IMPORTE_VENCIDO = 0;
      INTERES = 0;
      IMPORTE_A_VENCER = 0;
      DESCUENTO_VENCIDO = 0;
      DESCUENTO_A_VENCER = 0;
      DEUDA = 0;
      TOTAL = 0;
      COD_CAT_RECARGO = NULL;
      IF (:MOSTRAR_DEUDA = 1) THEN
      BEGIN
        SELECT C.CUOTA_DESDE, C.CUOTA_HASTA, C.IMPORTE_VENCIDO, C.INTERES,
          C.IMPORTE_A_VENCER, C.DESCUENTO_VENCIDO, C.DESCUENTO_A_VENCER,
          C.DEUDA, C.TOTAL, C.COD_CAT_RECARGO
        FROM CALCULAR_INTERES_CP(:CODIGO, :FECHA_INTERES, :FECHA_HASTA) C
        INTO :CUOTA_DESDE, :CUOTA_HASTA, :IMPORTE_VENCIDO, :INTERES, :IMPORTE_A_VENCER,
          :DESCUENTO_VENCIDO, :DESCUENTO_A_VENCER, :DEUDA, :TOTAL, :COD_CAT_RECARGO;
        IF (:CUOTA_DESDE IS NULL) THEN
        BEGIN
          SELECT MIN(C.FECHA_CUOTA)
          FROM CUOTAS_PERIODICAS C
          WHERE C.COD_CONFIGURACION = :CODIGO
          AND C.FECHA_RENDICION IS NULL AND C.ANULADO = 0
          AND C.REFINANCIADO_POR IS NULL
          AND C.INACTIVO = 0
          INTO :CUOTA_DESDE;
        END
        IF (:CUOTA_DESDE IS NULL) THEN
        BEGIN
          SELECT MAX(C.FECHA_CUOTA)
          FROM CUOTAS_PERIODICAS C
          WHERE C.COD_CONFIGURACION = :CODIGO
          AND C.FECHA_RENDICION IS NOT NULL
          INTO :CUOTA_DESDE;
          IF (:CUOTA_DESDE IS NOT NULL) THEN
          BEGIN
            EXECUTE PROCEDURE INCREMENTAR_FECHA :CUOTA_DESDE, 'Mes', 1
            RETURNING_VALUES :CUOTA_DESDE;
          END
        END
      END
    END
    SUSPEND;
  END
END^

SET TERM ;^
