/*
  MCP API v2 - comprobantes de propuesta con filtros de dominio.

  La fuente conserva el cálculo de pagos y estados de
  GET_COMPROBANTES_PROPUESTA, y agrega categoría de comprobante, código de
  cliente y el indicador booleano de anulación para consumidores v2.
*/

SET TERM ^;

CREATE OR ALTER PROCEDURE GET_COMPROBANTES_PROPUESTA_V2 (
    COD_PROPUESTA INTEGER,
    DESDE DATE,
    HASTA DATE,
    TIPO VARCHAR(30),
    ESTADO VARCHAR(30))
RETURNS (
    FECHA DATE,
    TIPO_COMPROBANTE VARCHAR(30),
    NRO_COMPROBANTE VARCHAR(30),
    COD_CLIENTE INTEGER,
    CLIENTE VARCHAR(100),
    TOTAL DECIMAL(18,2),
    PAGO DECIMAL(18,2),
    ESTADO_COMPROBANTE VARCHAR(30),
    ANULADO SMALLINT)
AS
BEGIN
  FOR
    SELECT CP.FECHA, TC.TIPO_COMPROBANTE, CP.NRO_COMPROBANTE,
      C.COD_CLIENTE, CP.CLIENTE, CP.TOTAL, CP.PAGO, CP.ESTADO,
      CASE CP.ANULADO WHEN 'SI' THEN 1 ELSE 0 END
    FROM GET_COMPROBANTES_PROPUESTA(:COD_PROPUESTA) CP
    INNER JOIN COMPROBANTES C ON C.COD_TALONARIO = CP.COD_TALONARIO
                            AND C.NRO_COMPROBANTE = CP.NRO_COMPROBANTE
    INNER JOIN TIPOS_COMPROBANTES TC ON TC.COD_TIPO_COMPROBANTE = C.COD_TIPO_COMPROBANTE
    WHERE (:DESDE IS NULL OR CP.FECHA >= :DESDE)
      AND (:HASTA IS NULL OR CP.FECHA <= :HASTA)
      AND (:TIPO IS NULL OR UPPER(TC.TIPO_COMPROBANTE) = UPPER(:TIPO))
      AND (:ESTADO IS NULL OR UPPER(CP.ESTADO) = UPPER(:ESTADO))
    ORDER BY CP.FECHA, CP.NRO_COMPROBANTE
    INTO :FECHA, :TIPO_COMPROBANTE, :NRO_COMPROBANTE,
      :COD_CLIENTE, :CLIENTE, :TOTAL, :PAGO, :ESTADO_COMPROBANTE, :ANULADO
  DO
  BEGIN
    SUSPEND;
  END
END^

SET TERM ;^
