/*
  MCP API v2 - relación verificable entre contrato y plan de venta.

  Aplicada manualmente en Firebird el 26/09/2026.
  La FK PLANES_VENTAS.COD_CONTRATO -> CONTRATOS.COD_CONTRATO es la fuente
  autoritativa de la asociación. El procedimiento expone ambas claves para
  que las fachadas no asocien contratos y planes por posición.
*/

SET TERM ^;

ALTER PROCEDURE GET_DATOS_DET_PLANES_VENTAS (
    COD_PROPUESTA INTEGER,
    MOSTRAR_BAJA SMALLINT)
RETURNS (
    PLAN_VENTA VARCHAR(100),
    CONCEPTO VARCHAR(100),
    TOTAL NUMERIC(18, 2),
    VIGENCIA_DESDE DATE,
    VIGENCIA_HASTA DATE,
    COD_PLAN_VENTA INTEGER,
    COD_CONTRATO INTEGER)
AS
BEGIN
  FOR
    SELECT
      (SELECT PM.NOMBRE FROM PLANES_VENTAS_MODELOS PM
       WHERE PM.COD_PLAN_VENTA_MODELO = P.COD_PLAN_VENTA_MODELO),
      D.DESCRIPCION, D.TOTAL, D.VIGENCIA_DESDE, D.VIGENCIA_HASTA,
      P.COD_PLAN_VENTA, P.COD_CONTRATO
    FROM DET_PLANES_VENTAS D
    INNER JOIN PLANES_VENTAS P ON P.COD_PLAN_VENTA = D.COD_PLAN_VENTA
    WHERE P.COD_PROPUESTA = :COD_PROPUESTA
      AND (:MOSTRAR_BAJA = 1 OR P.FECHA_BAJA IS NULL)
    ORDER BY P.FECHA, D.MOMENTO_FACTURACION, D.COD_DETALLE
    INTO :PLAN_VENTA, :CONCEPTO, :TOTAL, :VIGENCIA_DESDE, :VIGENCIA_HASTA,
      :COD_PLAN_VENTA, :COD_CONTRATO
  DO
  BEGIN
    SUSPEND;
  END
END^

SET TERM ;^
