/*
  Fecha: 2026-09-07
  Alcance: persistencia de solicitudes de recuperacion de clave de clientes.
  Impacto: agrega la tabla RECUPERACIONES_CLAVE, su generador, clave foranea e indices.

  El token se persiste exclusivamente como hash SHA-256 hexadecimal en TOKEN_HASH.
  PROPUESTA almacena el legajo recibido por la API; no referencia COD_PROPUESTA.
*/

CREATE TABLE RECUPERACIONES_CLAVE (
  COD_RECUPERACION  T_CLAVE_UNICA NOT NULL,
  COD_CLIENTE       T_CLAVE_UNICA NOT NULL,
  PROPUESTA         INTEGER NOT NULL,
  TOKEN_HASH        VARCHAR(64) NOT NULL,
  FECHA_CREACION    T_FECHA_HORA NOT NULL,
  FECHA_VENCIMIENTO T_FECHA_HORA NOT NULL,
  FECHA_UTILIZACION T_FECHA_HORA,
  IP_SOLICITUD      VARCHAR(45)
);

ALTER TABLE RECUPERACIONES_CLAVE
  ADD CONSTRAINT PK_RECUPERACIONES_CLAVE PRIMARY KEY (COD_RECUPERACION);

ALTER TABLE RECUPERACIONES_CLAVE
  ADD CONSTRAINT FK_RECUPERACIONES_1
  FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTES (COD_CLIENTE);

ALTER TABLE RECUPERACIONES_CLAVE
  ADD CONSTRAINT UQ_RECUPERACIONES UNIQUE (TOKEN_HASH);

CREATE INDEX IDX_RECUPERACIONES_CLAVE_1
  ON RECUPERACIONES_CLAVE (COD_CLIENTE, FECHA_UTILIZACION, FECHA_VENCIMIENTO);

CREATE INDEX IDX_RECUPERACIONES_CLAVE_2
  ON RECUPERACIONES_CLAVE (PROPUESTA, FECHA_CREACION);

CREATE INDEX IX_RECUPERACIONES_CLAVE_3
  ON RECUPERACIONES_CLAVE (IP_SOLICITUD, FECHA_CREACION);

CREATE GENERATOR GEN_RECUPERACIONES_CLAVE;

CREATE TRIGGER CRE_RECUPERACIONES_CLAVE FOR RECUPERACIONES_CLAVE
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.COD_RECUPERACION IS NULL) THEN
    BEGIN
        NEW.COD_RECUPERACION = GEN_ID(GEN_RECUPERACIONES_CLAVE, 1);

        EXECUTE PROCEDURE CONTROLAR_GENERADOR NEW.COD_RECUPERACION, 'RECUPERACIONES_CLAVE';
    END
END
;

EXECUTE PROCEDURE CFG$ACTUALIZAR_TABLAS_SISTEMA; COMMIT;
--SELECT * FROM CFG$GENERAR_BASE_SINCRONIZABLE(0)

INSERT INTO HIST_SCRIPTS_DB (NOMBRE_ARCHIVO)
VALUES ('260907 - Crear tabla de recuperaciones de clave.sql');
COMMIT;

