/*
  MCP API v2 - servicios normalizados para agentes.

  Expone los hechos ya calculados por CONSULTA_SERVICIOS_PROP en filas, sin
  títulos/mensajes posicionales de la grilla de frontend. Aplicada manualmente
  en Firebird el 26/09/2026.
*/

SET TERM ^;

CREATE OR ALTER PROCEDURE GET_SERVICIOS_PROPUESTA_V2 (
    COD_PROPUESTA INTEGER)
RETURNS (
    COD_SERVICIO_MODELO INTEGER,
    ORDEN INTEGER,
    COD_PLAN_VENTA INTEGER,
    MODELO VARCHAR(100),
    SERVICIO VARCHAR(100),
    EN_MORA SMALLINT,
    INHABILITADO_POR_MORA SMALLINT,
    HABILITADO SMALLINT,
    VIGENCIA_DESDE DATE,
    VIGENCIA_HASTA DATE,
    SUSPENDIDO_HASTA DATE,
    LIMITE_SERVICIOS INTEGER,
    SERVICIOS_REALIZADOS INTEGER,
    SERVICIOS_PENDIENTES INTEGER,
    UTILIZADO_TITULAR INTEGER,
    COD_CLIENTE INTEGER,
    CLIENTE VARCHAR(100),
    MAYOR_EDAD SMALLINT,
    COD_INHUMADO INTEGER,
    FECHA_CADUCIDAD DATE)
AS
BEGIN
  FOR
    SELECT C.COD_SERVICIO_MODELO, C.ORDEN, C.COD_PLAN_VENTA,
      C.MODELO, C.SERVICIO, C.EN_MORA, C.INHABILITADO_POR_MORA,
      C.HABILITADO, C.VIGENCIA_DESDE, C.VIGENCIA_HASTA,
      C.SUSPENDIDO_HASTA, C.LIMITE_SERVICIOS, C.SERVICIOS_REALIZADOS,
      C.SERVICIOS_PENDIENTES, C.UTILIZADO_TITULAR, C.COD_CLIENTE,
      (SELECT CL.NOMBRE FROM CLIENTES CL WHERE CL.COD_CLIENTE = C.COD_CLIENTE),
      C.MAYOR_EDAD, C.COD_INHUMADO,
      (SELECT PV.FECHA_CADUCIDAD FROM PLANES_VENTAS PV WHERE PV.COD_PLAN_VENTA = C.COD_PLAN_VENTA)
    FROM CONSULTA_SERVICIOS_PROP(:COD_PROPUESTA, 0) C
    INTO :COD_SERVICIO_MODELO, :ORDEN, :COD_PLAN_VENTA,
      :MODELO, :SERVICIO, :EN_MORA, :INHABILITADO_POR_MORA,
      :HABILITADO, :VIGENCIA_DESDE, :VIGENCIA_HASTA,
      :SUSPENDIDO_HASTA, :LIMITE_SERVICIOS, :SERVICIOS_REALIZADOS,
      :SERVICIOS_PENDIENTES, :UTILIZADO_TITULAR, :COD_CLIENTE,
      :CLIENTE, :MAYOR_EDAD, :COD_INHUMADO, :FECHA_CADUCIDAD
  DO
  BEGIN
    SUSPEND;
  END
END^

SET TERM ;^
